### ISSUE TITLE
Webtiles server not compatible with Python 3.13 due to deprication of `crypt` and issue with `subprocess`

### ISSUE THREAD

**Issue by EricFecteau** [crawl/crawl#4353]
# Issue for `crypt`

The `crypt` python library, used in [userdb.py](https://github.com/crawl/crawl/blob/master/crawl-ref/source/webserver/webtiles/userdb.py#L1), was [deprecated in Python 3.11 and removed in Python 3.13](https://docs.python.org/3/library/crypt.html). This was done in [PEP 594](https://docs.python.org/3/whatsnew/3.13.html#whatsnew313-pep594). This makes `dcss` webtile server not work with Python 3.13. 

You can use [standard-crypt](https://pypi.org/project/standard-crypt/) and [deprecated-crypt-alternative](https://pypi.org/project/deprecated-crypt-alternative/) to make it work temporarily.

# Issue with `subprocess`

Ok, this one I don't understand how it worked previously. I get `module 'subprocess' has no attribute 'signal'` issue in the [process_handler.py](https://github.com/crawl/crawl/blob/master/crawl-ref/source/webserver/webtiles/process_handler.py). 

You can fix this by importing `signal` instead and changing all the sections that say `subprocess.signal` to simply say `signal` (and rename some variables).

Once these two fixes are done, the webtiles server works like a charm again!

**Comment by nlavsky** [comment]
We've addressed these issues in 13813543 and c6c20554, so the webserver now supports Python 3.13. Thanks for the report!
